# To support special characters save in UTF-8
Settings:
    # Scheduler Interval in minutes
    Interval: 5
    # true: random | false: consecutive
    Random: false
    # true: permissions security | false: only OP's
    Permission: true
    # Tag for Announcement. May be empty: ''
    Tag: '&GOLD;[AutoAnnouncer]'
Announcer:
    # true: certain groups in permissions | false: to all
    ToGroups: false
    # Groups to send announcement.
    Groups:
        - 'default'
    # Strings to announce
    Strings:
        - '&DARK_RED;Running CraftBukkit server with &GOLD;AutoAnnouncer.'
        - '&DARK_GREEN;Development by Sharkiller!'