name: AutoAnnouncer
main: ar.com.sharkale.AutoAnnouncer.AutoAnnouncer
version: 1.6-03.10
author: Sharkiller
description: Global announcements every few minutes.
softdepend: [Vault] 
commands:
  announcer:
    description: Manage announcements
    usage: /<command> help - Help for AutoAnnouncer
permissions:
    announcer.admin:
        description: Allow to use AutoAnnouncer commands
        default: op